name: "ğŸ•› Set workout KR current prop"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      year:
        description: 'Year for the command'
        required: false
      month:
        description: 'Month for the command'
        required: false
jobs:
  run-command:
    runs-on: ubuntu-latest
    
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}

    steps:
      - name: "ğŸ“¦ Checkout"
        uses: actions/checkout@v2

      - name: "ğŸ” Set up Bun"
      - uses: oven-sh/setup-bun@v1
          
      - name: "ğŸƒâ€â™‚ï¸ Fetch value and set on Notion"
        run: bun run cli set-current-value-of-workout-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}
